### ISSUE TITLE
Getting project working with the latest package versions...

### ISSUE THREAD

**Issue by ttonyh** [jomurgel/project-acorn-ssr#2]
I'm trying to get this project to build after updating to the latest versions for all packages, as follows:

```
package.json
...
  "dependencies": {
    "axios": "^0.18.0",
    "build": "^0.1.4",
    "compression": "^1.7.2",
    "express": "^4.16.3",
    "lru-cache": "^4.1.2",
    "run": "^1.4.0",
    "sanitize.scss": "^1.0.0",
    "serve-favicon": "^2.5.0",
    "skeleton-scss": "^2.0.4",
    "start": "^5.1.0",
    "style-loader": "^0.20.3",
    "sw-precache-webpack-plugin": "^0.11.5",
    "vue": "^2.5.16",
    "vue-analytics": "^5.10.0",
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.5.16",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^8.2.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.24.1",
    "cross-env": "^5.1.4",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.2",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "glob": "^7.1.2",
    "node-sass": "^4.8.3",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "svg-sprite": "^1.4.0",
    "url-loader": "^1.0.1",
    "vue-loader": "^15.0.0-beta.7",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.4.1",
    "webpack-dev-middleware": "^3.1.0",
    "webpack-hot-middleware": "^2.21.2",
    "webpack-merge": "^4.1.2",
    "webpack-node-externals": "^1.7.2"
  }
...

```

I get the following error:

```
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

Since you're using Webpack 4 anyways, there are several migration tasks to do for full compatibility; here are some off the top of my head, and I apologize in advance, my Webpack expertise is very limited.

1. Using 'mode' property for development / production 
2. Removing deprecated / removed plugins
3. Replacing extract-text-webpack-plugin with mini-css-extract-plugin

I'm using the 'next' branch of vue-loader for all this to work. (noted above in package.json) and using a more recent version of Node (v9.8.0)

I have been trying and unfortunately, not able to get it to build; here's the error that I can't get past:

```
.../lib/node_modules/webpack-cli/bin/webpack.js:242
Error: invalid "instanceof" keyword value Promise
```

**Comment by jomurgel** [comment]
@ttonyh Noticed that today as well.  Thanks or the issue.

I pushed an update to master which downgrades to webpack 3.10.0 for now until I can handle some issue with:

- `webpack.optimize.CommonsChunkPlugin` which was removed in Webpack 4.x.
- `webpack-dev-middleware` and `webpack-hot-middleware` both newer versions were only work with Webpack 4.x.
- `webpack.optimize.UglifyJsPlugin` was moved into it's own package or needs to be replaced with Webpack 4.x's `optimizations` config.
- needs missing `mode`.

Among several others. I think I'd started building on Webpack 3 and updated without fully testing on updated dependencies. 🤦‍♂️ 

For now, the downgrading is a band-aid to get things working just until I have time to debug and go through and update the WebPack packages/configs. 

Pull master and `npm install` should right all the errors for now.

Feel free, if you've made any adjustments to get around those, issuing a PR. In either case, I'll be working to get everything working with 4.x.

**Comment by jomurgel** [comment]
@ttonyh issued a PR for... myself.... @ #3 which resolves the majority of the issues. Webpack 4 doesn't look to be 100% supported across the board but these updates get all the dependencies to current versions and the dev, build, and start scripts working. 

A few notes about warnings in there.

Will do some other digging and review before I merge it into master, but I think it's in good shape.

Thanks for bringing the issue to my attention!
