### ISSUE TITLE
Param ssrContext on createApp function not passed in

### ISSUE THREAD

**Issue by ttonyh** [jomurgel/project-acorn-ssr#4]
The ssrContext param that was added in the createApp function, never gets passed in. I've been trying to figure out how to get reference to "ssrContext" at the time that "createApp()" is called (in client-entry) and it doesn't seem to have reference.

**Comment by jomurgel** [comment]
@ttonyh the `ssrContext` is the variable being passed in from `entry-server.js` on [Line 10](https://github.com/jomurgel/project-acorn-ssr/blob/master/src/entry-server.js#L10) so would be undefined at the point that it is referenced in `app.js`.

If you're in your app instance you can access the `ssrContext` via `this.$ssrContext`, but you'd probably need to actually update the context you could do that inside the server.js file on [Line 150](https://github.com/jomurgel/project-acorn-ssr/blob/master/server.js#L150).

**Comment by ttonyh** [comment]
You are correct. I'm not quite sure what you'd do in this case. I need to do more research on this. Thanks for taking the time to reply.

**Comment by jomurgel** [comment]
What is it that you're trying to do, perhaps I can help point you in some direction...

**Comment by jomurgel** [comment]
Going to close this since it's been a while. Feel free to reach out if there are any other questions on the topic. 👍
